### ISSUE TITLE
Known issue: Unable to complete Frame Config at `1280x768` resolution.

### ISSUE THREAD

**Issue by HeroXx** [Xian55/WowClassicGrindBot#416]
### Description

I am running 1920x1080 with 100 scaling and cell size 1 and I cannot get past the setup phase.

![image](https://user-images.githubusercontent.com/480522/188233833-e63f2208-802d-4386-a02a-eb929aa0bccb.png)

### Addon Version

1.7.17

### World of Warcraft Client

Wrath of the Lich King Classic

### Reproduction Steps

Attempt to run setup on a non VM

### Last Good Version

N/A

**Comment by Xian55** [comment]
Hi based on the provided image that dosen't seems to be cell size 1, but much bigger.

I require log message as well in order to proceed further investigation

**Comment by HeroXx** [comment]
I reset everything with the same result:

![image](https://user-images.githubusercontent.com/480522/188235655-85913a9e-661d-41bc-8784-42175691762c.png)

```
[22:10:35:408 INF] Found WowProcess
[22:10:35:438 INF] Client window: {X=640,Y=323,Width=1280,Height=768}
[22:10:35:468 INF] Addon installed! Version: 1.7.17
[22:10:35:469 INF] Enter configuration mode.
[22:10:35:973 INF] /fester
[22:10:36:728 INF] Addon installed! Version: 1.7.17
[22:10:36:730 INF] Enter configuration mode.
[22:10:37:239 INF] /fester
[22:10:38:026 INF] DataFrameMeta: hash: 10201100 | spacing: 1 | size: 2 | rows: 1 | frames: 100
[22:10:38:081 INF] Exit configuration mode.
[22:10:38:082 INF] /fester
[22:10:39:664 ERR] Unable to identify ClientVersion UnitRace and UnitClass!
[22:10:39:666 INF] Frame configuration was incomplete! Please try again, after resolving the previusly mentioned issues...
```

**Comment by Xian55** [comment]
Just did a quick test,
- 1280x720
- 1280x680
yields the same issue.

Can you try a different resolution such as 
* 1024x768
* 1280x960
?

**Comment by HeroXx** [comment]
Same issue on 1024x768:

![image](https://user-images.githubusercontent.com/480522/188236754-ab53870a-667e-49f2-b01d-0e63af37d191.png)

![image](https://user-images.githubusercontent.com/480522/188236788-d9071bd3-2078-4e77-b583-c7e8ccc757b7.png)

**Comment by Xian55** [comment]
can you try increase the cell size to **2** at least ?

On the other hand be sure to only one instance of the addon is installed.

Currently your addon name is called **fester**

**Comment by Xian55** [comment]
Are you using any kind of post processing application such as Reshade, which is capable of changing the output pixel color?

On the other hand it is super important to disable glow effect as it affects the UI color.

You can disable the glow by typing in game the `/console ffxGlow 0` command, and be sure to properly quit the game. ESC -> Exit Game, in order to save the settings.

**Comment by HeroXx** [comment]
I only have a single addon of the data grid installed and no I am not using reshade. Cell size 2 made no difference.

![image](https://user-images.githubusercontent.com/480522/188237290-2e1503b0-cc2e-4d2f-b4f5-6ad9c851533c.png)

Does this work on Windows 11?

**Comment by Xian55** [comment]
Are you using any kind of `Image Sharpening` application, such as in the AMD radeon driver or in Nvidia control panel?

**Comment by HeroXx** [comment]
No, I followed the guide and checked Nvidia Control panel for those settings.

**Comment by Xian55** [comment]
> Does this work on Windows 11?

Personally i have not tested, nor i can validate.

**Comment by Xian55** [comment]
May i ask you to try out in full screen mode?

**Comment by Xian55** [comment]
Blizzard just posted a new patch, and the addon yields lua errors.

You can enable to show lua errors by `/console scriptErrors 1`

For me it shows 

![image](https://user-images.githubusercontent.com/367101/188237916-8460227b-7d7b-43de-a6a9-a55895869bda.png)

If you wish to disable it type `/console scriptErrors 0`

**Comment by HeroXx** [comment]
Yes I also get a large amount of errors, I assumed it was just something everyone got

**Comment by Xian55** [comment]
Give me a few minutes, fix is on the way!

**Comment by HeroXx** [comment]
![image](https://user-images.githubusercontent.com/480522/188238051-a0050050-8fc6-4d2c-8e1e-090e3ab9d56f.png)

**Comment by HeroXx** [comment]
Changing versions.lua to:

```
if WOW_PROJECT_ID == WOW_PROJECT_MAINLINE then
	DataToColor.ClientVersion = 1
elseif WOW_PROJECT_ID == WOW_PROJECT_BURNING_CRUSADE_CLASSIC or WOW_PROJECT_ID == WOW_PROJECT_WRATH_CLASSIC then
	if LE_EXPANSION_LEVEL_CURRENT == LE_EXPANSION_NORTHREND or LE_EXPANSION_LEVEL_CURRENT == LE_EXPANSION_WRATH_OF_THE_LICH_KING then
		DataToColor.ClientVersion = 4
	elseif LE_EXPANSION_LEVEL_CURRENT == LE_EXPANSION_BURNING_CRUSADE then
		DataToColor.ClientVersion = 3
	end
elseif WOW_PROJECT_ID == WOW_PROJECT_CLASSIC then
	DataToColor.ClientVersion = 2
end
```
Fixed that issue for me, but now I have:
![image](https://user-images.githubusercontent.com/480522/188239043-a107a8c3-1408-44ac-b86c-3d2c6131f1cd.png)

**Comment by Xian55** [comment]
https://github.com/Xian55/WowClassicGrindBot/pull/417 is up the lua errors should gone.

However the 1280x768 resolution still not working, my initial guess is scaling issue.

May i recommend to try out 1024x768 or 1280x960 resolutions ? 

Let me know your results!

**Comment by HeroXx** [comment]
Thank you, it appears to be working on 1920x1080. My final question, should the mage profile lvl 1 always try to approach the mob? it just approaches and cancels the cast constantly.

**Comment by Xian55** [comment]
It was a long time since i spent time on level 1 profiles.

Many sub system has been changed since, it is possible i broke compatibility, sadly.

**Comment by Xian55** [comment]
You can try this construct

```json
  "Pull": {
    "Sequence": [
      {
        "Name": "Fireball",
        "Key": "2",
        "HasCastBar": true,
        "Requirement": "Mana% > MIN_MANA_FIREBALL%",
        "AfterCastWaitCastbar": true
      },
      {
        "Name": "Approach",
        "Log": false
      }
    ]
  },
  ```

**Comment by Xian55** [comment]
I updated the docs about [Casting Handler](https://github.com/Xian55/WowClassicGrindBot#casting-handler)

**Comment by HeroXx** [comment]
Thank you. That seems to make it better but it does seem to interrupt itself quite a bit:

```
... AfterCastWaitCastbar(h) 1092ms or interrupt...
```

**Comment by Xian55** [comment]
Going to look at it later, thanks for the report!

Blizz might changed something with the latest patch.

Like adding this `WOW_PROJECT_WRATH_CLASSIC` seems really lame, especially the prepatch is out from couple of days.

**Comment by Xian55** [comment]
oh i see there are more lua errors :(

**Comment by Xian55** [comment]
https://github.com/Xian55/WowClassicGrindBot/pull/418 should fix casting problems!
